name: PHP Shell Image Builder

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: Login to Registry
        env:
          DOCKER_USER: ${{ secrets.NAME }}
          DOCKER_PASSWORD: ${{ secrets.SECRET }}
          REGISTRY: ${{ secrets.REGISTRY }}
          PROJECT: ${{ secrets.PROJECT }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY
          echo "TAG=`date +%Y.%m.%d.%H.%M.%S`" >> $GITHUB_ENV
          echo "REGISTRY=$REGISTRY/$PROJECT" >> $GITHUB_ENV
          echo "POLICY=jtb75-vuln-policy" >> $GITHUB_ENV
      - name: Build the Docker image
        working-directory: ./
        run: |
          docker build . --file Dockerfile --tag $REGISTRY/php-shell:$TAG --tag $REGISTRY/php-shell:latest
      - name: Download and Authenticate Wiz CLI
        env:
          WIZ_USER: ${{ secrets.WIZ_USER }}
          WIZ_SECRET: ${{ secrets.WIZ_SECRET }}
        working-directory: ./
        run: |
          curl -Lo wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64;
          chmod 755 ./wizcli;
          ./wizcli auth --id $WIZ_USER --secret $WIZ_SECRET;
      - name: Scan the Docker Image
        working-directory: ./
        run: |
          ./wizcli docker scan --image $REGISTRY/php-shell:$TAG --policy $POLICY
      - name: Push the Docker image
        run: |
          docker push $REGISTRY/php-shell:$TAG
          docker push $REGISTRY/php-shell:latest